// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btlwicqylyyrjonxumjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0bHdpY3F5bHl5cmpvbnh1bWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODM0NDAsImV4cCI6MjA3MDI1OTQ0MH0.k1WDcd3tS6jm0Rp9xq3dsR-Ze90tBjs_n-sKjeo4EFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});